#!/usr/bin/env ruby
#^syntax detection

forge "https://forge.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
# mod 'puppetlabs-stdlib'
mod 'hunner-hiera', '1.2.0'
mod 'mthibaut-users', '1.0.11'
mod 'puppetlabs-stdlib', '4.5.1'
mod 'puppetlabs-concat', '1.2.0'
mod 'saz-sudo', '3.0.9'

# A module from git
# mod 'puppetlabs-ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
